from datetime import datetime
from enum import Enum
from pydantic import BaseModel
from typing import Optional

class Priority(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"

class Task(BaseModel):
    id: int  # numeric, auto-generated by database
    title: str
    completed: bool = False
    priority: Priority = Priority.medium
    createdAt: datetime  # stored as datetime; serializes to ISO 8601 in JSON
    updatedAt: Optional[datetime] = None

class TaskCreate(BaseModel):
    """Request body for creating a task (id and timestamps are set by backend)."""
    title: str
    completed: bool = False
    priority: Priority = Priority.medium

class TaskUpdate(BaseModel):
    """Request body for PATCH: only include fields that change."""
    title: Optional[str] = None
    completed: Optional[bool] = None
    priority: Optional[Priority] = None