export type Priority = 'low' | 'medium' | 'high';

export interface Task {
  id: number; // numeric, auto-generated by database
  title: string;
  completed: boolean;
  priority: Priority;
  createdAt: string; // ISO 8601 datetime from API (e.g. "2026-02-09T12:00:00")
  updatedAt?: string; // ISO 8601 datetime, or undefined if never updated
}
